// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetFeature(ctx context.Context, id uuid.UUID) (Feature, error)
	ListFeatures(ctx context.Context, arg ListFeaturesParams) ([]Feature, error)
}

var _ Querier = (*Queries)(nil)
