DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS profile_permissions;
DROP TABLE IF EXISTS permission_features;
DROP TABLE IF EXISTS profiles;
DROP TABLE IF EXISTS permissions;
DROP TABLE IF EXISTS features;
DROP TYPE IF EXISTS user_status;
DROP TYPE IF EXISTS profile_type;
DROP TYPE IF EXISTS permission_type;